version: '3'
services:
  airflow-webserver:
    image: apache/airflow:2.3.0-python3.10
    command: webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:gSyOrnLn2bF9uX5Kw0WV85AIokPfKh6c@dpg-co4keh779t8c7393go9g-a.singapore-postgres.render.com/userstats
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=secret_key_here
      - AIRFLOW_UID=${UID:-50000}
      - AIRFLOW_GID=0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler

  airflow-scheduler:
    image: apache/airflow:2.3.0-python3.10
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:gSyOrnLn2bF9uX5Kw0WV85AIokPfKh6c@dpg-co4keh779t8c7393go9g-a.singapore-postgres.render.com/userstats
      - AIRFLOW_UID=${UID:-50000}
      - AIRFLOW_GID=0
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
