version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: leetcode_stats
    ports:
      - "5432:5432"
  
  airflow:
    image: apache/airflow:latest
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/leetcode_stats
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_UID: "1000"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      # Temporarily commented out to allow Airflow to set up logs directory
      # - ./logs:/opt/airflow/logs
    user: "${UID:-1000}:${GID:-0}"
